// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ItemDetailsResponse struct {
	ID        int            `json:"id"`
	Name      string         `json:"name"`
	ImageURL  string         `json:"imageUrl"`
	Nutrition *NutritionFact `json:"nutrition"`
	User      *UserDetails   `json:"user"`
}

type NutritionFact struct {
	Calories *float64 `json:"calories"`
	Protein  *float64 `json:"protein"`
	Fat      *float64 `json:"fat"`
}

type Process struct {
	ProcessID int     `json:"processId"`
	Heading   string  `json:"heading"`
	Content   string  `json:"content"`
	ImageURL  *string `json:"imageUrl"`
}

type UserDetails struct {
	UserID  int    `json:"userId"`
	Name    string `json:"name"`
	Address string `json:"address"`
}
